# ==============================================================================
# USER CONFIGURATION: appearance.conf
# ==============================================================================
# Add your custom settings for appearance here.
# These will override or add to the defaults found in ~/.config/hypr/source/appearance.conf
# ==============================================================================

# Disable animations for better performance
animations {
    enabled = false
}

# Custom Appearance Settings
decoration {
    # Enable shadows
    shadow {
        enabled = true
    }
    
    # Enable blur
    blur {
        enabled = true
    }
}

# Opacity for all windows (active, inactive)
windowrule = opacity 0.9 0.6, match:class .*
