# ==============================================================================
# USER CONFIGURATION: input.conf
# ==============================================================================
# Add your custom settings for input here.
# These will override or add to the defaults found in ~/.config/hypr/source/input.conf
# ==============================================================================

# Keyboard settings
input {
    left_handed = false
    
    touchpad {
        # Mac-style right click with 2-finger tap
        clickfinger_behavior = true
    }
}

# Per-device settings
device {
    name = epic-mouse-v1
    sensitivity = 0
}
